/*
 * LoginFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ly.view;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.ly.bean.User;
import com.ly.service.LoginCheck;

/**
 *
 * @author  __USER__
 */
public class LoginFrm extends javax.swing.JFrame {

	private User loginUser;

	/** Creates new form LoginFrm */
	public LoginFrm() {
		initComponents();
	}

	public LoginFrm(User loginUser) {
		this.loginUser = loginUser;
		initComponents();

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		loginTitleLabel = new javax.swing.JLabel();
		usernameField = new javax.swing.JTextField();
		usernameLabel = new javax.swing.JLabel();
		passwordLabel = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		loginButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();

		org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 400,
				Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		loginTitleLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 24));
		loginTitleLabel
				.setText("\u8f66\u961f\u7ba1\u7406\u7cfb\u7edf\u767b\u5f55");

		usernameLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18));
		usernameLabel.setText("\u7528\u6237\u540d");

		passwordLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18));
		passwordLabel.setText("\u5bc6\u7801");

		loginButton.setText("\u767b\u5f55");
		loginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginButtonActionPerformed(evt);
			}
		});

		resetButton.setText("\u91cd\u7f6e");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap(
																				109,
																				Short.MAX_VALUE)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												usernameLabel)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.UNRELATED))
																						.add(
																								layout
																										.createSequentialGroup()
																										.add(
																												layout
																														.createParallelGroup(
																																org.jdesktop.layout.GroupLayout.TRAILING)
																														.add(
																																loginButton)
																														.add(
																																passwordLabel))
																										.add(
																												23,
																												23,
																												23)))
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(
																								layout
																										.createParallelGroup(
																												org.jdesktop.layout.GroupLayout.LEADING,
																												false)
																										.add(
																												jPasswordField1,
																												0,
																												0,
																												Short.MAX_VALUE)
																										.add(
																												usernameField,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												137,
																												Short.MAX_VALUE))
																						.add(
																								resetButton)))
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																layout
																		.createSequentialGroup()
																		.add(
																				115,
																				115,
																				115)
																		.add(
																				loginTitleLabel,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				211,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(127, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(42, 42, 42)
										.add(loginTitleLabel)
										.add(44, 44, 44)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																usernameField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(usernameLabel))
										.add(32, 32, 32)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(passwordLabel)
														.add(
																jPasswordField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(29, 29, 29)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(loginButton).add(
																resetButton))
										.addContainerGap(53, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		jPasswordField1.setText("");
		usernameField.setText("");
	}

	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
		loginUser = null;
		String username = usernameField.getText();
		String password = jPasswordField1.getText();
		LoginCheck loginCheck = new LoginCheck();
		loginUser = loginCheck.loginCheck(username, password);
		if (loginUser != null) {
			this.dispose();
			MainFrm mainFrm = new MainFrm(loginUser);
			mainFrm.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "ÓÃ»§Ãû»òÃÜÂë´íÎó", "µÇÂ¼Ê§°Ü", 0);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		final LoginFrm loginFrm = new LoginFrm();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
				loginFrm.setLocation((dim.width - loginFrm.getWidth()) / 2,
						(dim.height - loginFrm.getHeight()) / 2);
				loginFrm.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JFrame jFrame1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JButton loginButton;
	private javax.swing.JLabel loginTitleLabel;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JButton resetButton;
	private javax.swing.JTextField usernameField;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration//GEN-END:variables

}