/*
 * MainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.ly.view;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;

import com.ly.bean.User;
import com.ly.service.FleetTableSV;

/**
 *
 * @author  __USER__
 */
public class MainFrm extends javax.swing.JFrame {

	private User loginUser;
	Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

	/** Creates new form MainFrm */
	public MainFrm() {
		initComponents();
	}

	public MainFrm(User loginUser) {
		this.loginUser = loginUser;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		searchMenuItem = new javax.swing.JMenuItem();
		checkInputMenuItem = new javax.swing.JMenuItem();
		checkPendingMenuItem = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		jFrame1.setTitle("\u8f66\u961f\u7ba1\u7406\u7cfb\u7edf");

		org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 400,
				Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu3.setText("\u5f55\u5165");

		jMenuItem1.setText("\u65b0\u5efa\u5f55\u5165");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem1);

		jMenuBar1.add(jMenu3);

		jMenu4.setText("\u67e5\u8be2");
		jMenu4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					searchMenuActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		searchMenuItem.setText("\u67e5\u8be2\u6570\u636e");
		searchMenuItem
		.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					searchMenuItemActionPerformed(evt);
				} catch (PropertyVetoException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jMenu4.add(searchMenuItem);
		

		checkInputMenuItem.setText("\u5f85\u5f55\u5165\u6570\u636e");
		jMenu4.add(checkInputMenuItem);

		checkPendingMenuItem.setText("\u5f85\u5ba1\u6838\u6570\u636e");
		checkPendingMenuItem
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						try {
							checkPendingMenuItemActionPerformed(evt);
						} catch (PropertyVetoException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
				});
		jMenu4.add(checkPendingMenuItem);
		if("后勤".equals(loginUser.getLevel())){
			checkPendingMenuItem.setVisible(false);
		}
		jMenuBar1.add(jMenu4);

		jMenuBar1.add(jMenu1);
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(table,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1280,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(57, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(table,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void checkPendingMenuItemActionPerformed(
			java.awt.event.ActionEvent evt) throws PropertyVetoException {
		ShowCheckPendFrm showCheckPendFrm = new ShowCheckPendFrm();
		this.getTable().add(showCheckPendFrm);
		showCheckPendFrm.setMaximum(true);
		showCheckPendFrm.setVisible(true);
	}

	private void searchMenuItemActionPerformed(java.awt.event.ActionEvent evt)
			throws PropertyVetoException {
		if ("主管".equals(loginUser.getLevel())) {
			SearchFleetTableFrm searchFleetTableFrm = new SearchFleetTableFrm(
					loginUser);
			this.getTable().add(searchFleetTableFrm);
			searchFleetTableFrm.setMaximum(true);
			searchFleetTableFrm.setVisible(true);
		} else {
			SearchFleetTableFrmByHouqin searchFleetTableFrmByHouqin = new SearchFleetTableFrmByHouqin(
					loginUser);
			this.getTable().add(searchFleetTableFrmByHouqin);
			searchFleetTableFrmByHouqin.setMaximum(true);
			searchFleetTableFrmByHouqin.setVisible(true);
		}

	}

	private void searchMenuActionPerformed(ActionEvent evt) {
		FleetTableSV fleetTableSV = new FleetTableSV();
		int count = fleetTableSV.getCountOfCheckPendFleetTableBean();
		checkPendingMenuItem.setText("待审核数据（"+count+"）");
	}
	
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		InputFrm inputFrm = new InputFrm(loginUser);
		this.table.add(inputFrm);
		inputFrm.setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem checkInputMenuItem;
	private javax.swing.JMenuItem checkPendingMenuItem;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem searchMenuItem;
	private static javax.swing.JDesktopPane table;

	// End of variables declaration//GEN-END:variables

	public static javax.swing.JDesktopPane getTable() {
		return table;
	}
}